### ISSUE TITLE
signal arrived during external code execution

### ISSUE THREAD

**Issue by Phuong39** [rafael-santiago/aegis#1]
i complied it on my PC, it working as well, but can not run on others PC

E:\test>main2
Exception 0xc0000005 0x1 0x7ff66669e000 0x29a2fac6189
PC=0x29a2fac6189
signal arrived during external code execution
```

runtime.cgocall(0x7ff6662355c0, 0xc000036ee0)
        runtime/cgocall.go:156 +0x4a fp=0xc0000cfd28 sp=0xc0000cfcf0 pc=0x7ff6661d472a
syscall.Syscall(0x29a08cc0000, 0x0, 0x0, 0x0, 0x0)
        runtime/syscall_windows.go:479 +0xf4 fp=0xc0000cfd60 sp=0xc0000cfd28 pc=0x7ff666230214
syscall.Syscall(0xc0000d97d0, 0xc00000c918, 0x3, 0x3, 0x7ff6663f9ae0)
        <autogenerated>:1 +0x2b fp=0xc0000cfdb0 sp=0xc0000cfd60 pc=0x7ff66623646b
main.frKGmicM({0xc0001ac500, 0x4d4})
        AL2ywal3.go:1 +0x41f fp=0xc0000cff28 sp=0xc0000cfdb0 pc=0x7ff6663d9bbf
main.main()
        qfQboakE.go:1 +0x17d fp=0xc0000cff80 sp=0xc0000cff28 pc=0x7ff6663db39d
runtime.main()
        runtime/proc.go:255 +0x217 fp=0xc0000cffe0 sp=0xc0000cff80 pc=0x7ff666208f37
runtime.goexit()
        runtime/asm_amd64.s:1581 +0x1 fp=0xc0000cffe8 sp=0xc0000cffe0 pc=0x7ff666233d61

goroutine 9 [chan receive]:
main.main.func2(0x0)
        GKVzJ9sN.go:2 +0xa6
created by main.main
        EDfnoW0i.go:4 +0xea

goroutine 24 [syscall]:
os/signal.signal_recv()
        runtime/sigqueue.go:169 +0x98
os/signal.loop()
        os/signal/signal_unix.go:24 +0x19
created by os/signal.Notify.func1.1
        os/signal/signal.go:151 +0x2c

goroutine 7 [IO wait]:
internal/poll.runtime_pollWait(0x29a2ddea728, 0x72)
        runtime/netpoll.go:229 +0x89
internal/poll.(*pollDesc).wait(0xb82282369d85d2ff, 0x8c52ccb7c05858db, 0x0)
        internal/poll/fd_poll_runtime.go:84 +0x32
internal/poll.execIO(0xc0000d4f18, 0x7ff6664b0108)
        internal/poll/fd_windows.go:175 +0xe5
internal/poll.(*FD).Read(0xc0000d4f00, {0xc0001ba000, 0x3e1c, 0x3e1c})
        internal/poll/fd_windows.go:441 +0x25f
net.(*netFD).Read(0xc0000d4f00, {0xc0001ba000, 0x7ff66663f640, 0xc0001257a8})
        net/fd_posix.go:56 +0x29
net.(*conn).Read(0xc000006010, {0xc0001ba000, 0x0, 0xc0001257f0})
        net/net.go:183 +0x45
crypto/tls.(*atLeastReader).Read(0xc00009e2d0, {0xc0001ba000, 0x0, 0x7ff6661da3cd})
        crypto/tls/conn.go:777 +0x3d
bytes.(*Buffer).ReadFrom(0xc00004a278, {0x7ff6664f6e60, 0xc00009e2d0})
        bytes/buffer.go:204 +0x98
crypto/tls.(*Conn).readFromUntil(0xc00004a000, {0x29a2de20008, 0xc000006010}, 0x0)
        crypto/tls/conn.go:799 +0xe5
crypto/tls.(*Conn).readRecordOrCCS(0xc00004a000, 0x0)
        crypto/tls/conn.go:606 +0x112
crypto/tls.(*Conn).readRecord(...)
        crypto/tls/conn.go:574
crypto/tls.(*Conn).Read(0xc00004a000, {0xc00019d000, 0x1000, 0x8010001})
        crypto/tls/conn.go:1277 +0x16f
bufio.(*Reader).Read(0xc0001984e0, {0xc000184498, 0x9, 0xc000125d30})
        bufio/bufio.go:227 +0x1b4
io.ReadAtLeast({0x7ff6664f6d80, 0xc0001984e0}, {0xc000184498, 0x9, 0x9}, 0x9)
        io/io.go:328 +0x9a
io.ReadFull(...)
        io/io.go:347
net/http.http2readFrameHeader({0xc000184498, 0x9, 0xc0000d9ec0}, {0x7ff6664f6d80, 0xc0001984e0})
        net/http/h2_bundle.go:1553 +0x6e
net/http.(*http2Framer).ReadFrame(0xc000184460)
        net/http/h2_bundle.go:1811 +0x95
net/http.(*http2clientConnReadLoop).run(0xc000125fa0)
        net/http/h2_bundle.go:8428 +0x165
net/http.(*http2ClientConn).readLoop(0xc000048180)
        net/http/h2_bundle.go:8350 +0x79
created by net/http.(*http2Transport).newClientConn
        net/http/h2_bundle.go:7302 +0xb45
rax     0x0
rbx     0x29a2fac603e
rcx     0x4c000
rdi     0x7ff66669e000
rsi     0xcc000c
rbp     0xbb51bff850
rsp     0xbb51bff750
r8      0x1e7
r9      0x5d
r10     0x17
r11     0x246
r12     0xc0000cfd10
r13     0x0
r14     0xbb51bff9b0
r15     0x6
rip     0x29a2fac6189
rflags  0x10246
cs      0x33
fs      0x53
gs      0x2b
```

**Comment by rafael-santiago** [comment]
Hi!

At first glance it seems to be a problem with your code but just by watching the stack trace I cannot tell you more. If you eliminate Aegis from the equation, does your app would continue failing to start? 

Do the provided Aegis samples work on those other PCs? Did you try to build this piece of code on the failure environment?

How are you actually using Aegis stuff into your code?
